name: Build and Upload Artifact

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'
          architecture: 'x64'
      
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      
      - name: Install PyInstaller
        run: |
          pip install pyinstaller
      
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile FluidFrames.RIFE.py
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows_FluidFrames.RIFE
          path: dist/FluidFrames.RIFE.exe
